apiVersion: v1
kind: Pod
metadata:
  name: trackr-portail
  labels:
    app.kubernetes.io/name: trackr-portail
    app.kubernetes.io/part-of: trackr
spec:
  initContainers:
    - name: prepare-page
      image: busybox:1.37
      command: ["sh", "-c", "echo '<h1>TrackR - portail Logivia</h1>' > /html/index.html; echo page generee"]
      volumeMounts:
        - { name: html, mountPath: /html }
      resources:
        requests: { cpu: "10m", memory: "8Mi" }
        limits:   { cpu: "50m", memory: "16Mi" }
    - name: log-agent
      image: busybox:1.37
      restartPolicy: Always          # => sidecar natif
      command: ["sh", "-c", "touch /logs/access.log; exec tail -F /logs/access.log"]
      volumeMounts:
        - { name: logs, mountPath: /logs }
      resources:
        requests: { cpu: "10m", memory: "8Mi" }
        limits:   { cpu: "50m", memory: "16Mi" }
  containers:
    - name: web
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - { name: html, mountPath: /usr/share/nginx/html }
        - { name: logs, mountPath: /var/log/nginx }   # remplace les liens vers stdout par de vrais fichiers
      resources:
        requests: { cpu: "20m", memory: "16Mi" }
        limits:   { cpu: "100m", memory: "64Mi" }
  volumes:
    - name: html
      emptyDir: {}
    - name: logs
      emptyDir: {}
